config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "pets#index"
  resources :pets, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pet.rb
class Pet < ApplicationRecord
  SPECIES = ["dog", "cat", "bird", "turtle", "alumni"]
  validates :name, presence: true
  validates :species, inclusion: {in: SPECIES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :set_pet, only: [:show, :edit, :update, :destroy]

  def index
    @pets = Pet.all
  end

  def show
    @days_ago = found_days_ago(@pet)
  end

  def edit
  end

  def update
    @pet.update(pet_params)
    redirect_to pet_path(@pet)
  end

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    @pet.save
    redirect_to pet_path(@pet)
  end

  def destroy
    @pet.destroy
    redirect_to root_path, status: :see_other
  end

  private

  def pet_params
    params.require(:pet).permit(:name, :address, :species, :found_on)
  end

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def found_days_ago(pet)
    (Date.today - pet.found_on).to_i
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LostPets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pets/_form.html.erb
<%#= simple_form_for pet do |f| %>
  <%#= f.label :name %>
  <%#= f.text_field :name %>
  <%#= f.label :address %>
  <%#= f.text_field :address %>
  <%#= f.label :species %>
  <%#= f.select :species, collection: Pet::SPECIES %>
  <%#= f.label :found_on %>
  <%#= f.date_field :found_on %>
  <%#= f.submit %>
<%# end %>
<div class="container my-4">
  <%= simple_form_for @pet do |f| %>
    <%= f.input :name, label: "Nom" %>
    <%= f.input :address %>
    <%= f.input :species, collection: Pet::SPECIES %>
    <%= f.input :found_on, html5: true %>
    <%= f.submit class: "btn btn-secondary mt-4" %>
  <% end %>
</div>

app/views/pets/edit.html.erb
<h1>Pet edition</h1>

<%= render 'form', pet: @pet %>

app/views/pets/index.html.erb
<div class="container my-4">
  <h1>Pets index</h1>
  <ul>
    <% @pets.each do |pet| %>
      <li>
        <%= pet.name %> |
        <%= pet.species %> |
        <%= pet.address %> |
        <%= pet.found_on %> |
        <%= link_to 'see details', pet_path(pet), class: "btn btn-primary" %>
      </li>
    <% end %>
  </ul>
  <p>
    <%= link_to 'Create new pet', new_pet_path, class: "btn btn-primary" %>
  </p>
</div>

app/views/pets/new.html.erb
<h1>Create new pet</h1>

<%= render 'form', pet: @pet %>

app/views/pets/show.html.erb
<h1>Pet</h1>
<%= @pet.name %>, <%= @pet.species %> found <%= @days_ago %> days ago in <%= @pet.address %>
<%= link_to 'Delete pet', pet_path(@pet), data: { turbo_method: :delete, turbo_confirm: "Are you sure ?" } %>